#!/usr/bin/env bash

#
# Performs checks of various things, typically TODO items.  For example, the 
# phrase 'method signature' was originally used in the code but was replaced 
# with 'expectation' as understanding of the problem space improved.  Below 
# is a check using grep to find and report all occurrences of 'signature' in 
# source and test code.
#
# Warning: the checks are not sophisticated.
#

echo 'Check for occurrences of 'signature' (should use 'expectation' instead) ...'
egrep -rin 'signature' src/*.coffee test/*.coffee

echo 'Check for private functions not beginning with underscore (_) ...'
egrep -rin '^[ ]+[a-z][a-z_]*[ ]*=.*->' src/*.coffee

echo 'Check for capitalization in test descriptions ...'
egrep -rn $'(describe|it)[ ]+[\'"][A-Z]' test/*.coffee

echo 'Check for non-https protocols on urls in package.json ...'
egrep $'[\'"]url[\'"][ ]*:' package.json | egrep -v 'https:'

echo 'Check for occurrences of 'exception' (should use 'error' instead) ...'
egrep -rin 'exception' src/*.coffee test/*.coffee

echo 'Check for .only and .skip tests ...'
egrep -rin '\.(only|skip) ' test/*.coffee

echo 'Check Travis CI config file .travis.yml ...'
QUIET=1 travis-lint

echo 'Check for tabs in source code files ...'
egrep -rn '\t' src/*.coffee test/*.coffee

echo 'Check for trailing spaces in source code files ...'
egrep -rn ' $' src/*.coffee test/*.coffee
